Schaefer dev
nasa/CompDam_DGD pull request #6
Opened 2018-10-04 12:21 UTC by stewartboyd119

The feature flag is slot 2 (prepeak nonlinearity)
with a flag value=5 for schaefer.

1. Updated plasticity to have additional args needed for schaefer
2. Added additional material properties

Added test coverage for OAT30, 60, 75, and 90
and compare to known non linear stress strain
responses

2018-10-04 18:10 UTC, aFrankLion commented on for/schaefer.for
> +      if (residual .lt. 1e-6) THEN
For all convergence criteria and loop limits, please either define a named, commented variables in the subroutine, e.g.,
schaefer_nr_tolerance = 1d-6  ! convergence criterion for Newton-Raphson loop
counter_limit =1000000  ! maximum number of Newton-Raphson loops before divergence is assumed
...or create user-definable parameters and add them to the parameters module.

2018-10-04 19:52 UTC, aFrankLion requested changes
Great work!

Why is tests/fakemat.props added instead of updating the existing .props file?

2018-10-04 19:52 UTC, aFrankLion commented on for/matProp.for
> +    Double Precision :: a6, b2, n, A                                       ! Specified parameters for schaefer theory
I'm concerned about the very generic names n and A. Consider creating more descriptive names to avoid confusion.

2018-10-08 01:21 UTC, stewartboyd119 commented on for/schaefer.for
> +      if (residual .lt. 1e-6) THEN
Created local variables per your suggestion. For simplicity, now I haven't put these in the parameters module though its probably a better solution in the long term

2018-10-08 01:22 UTC, stewartboyd119 commented on for/matProp.for
> +    Double Precision :: a6, b2, n, A                                       ! Specified parameters for schaefer theory
I changed these variables (and the associated properties file) to now have schaefer_a6, schaefer_b2...

2018-10-08 01:23 UTC, stewartboyd119 commented on for/matProp.for
> +    Double Precision :: a6, b2, n, A                                       ! Specified parameters for schaefer theory
I was using fakemat.props for convenience originally. I merged the additional parameters into IM7-8552.props and updated the tests to use it as well

2018-10-09 19:45 UTC, aFrankLion requested changes
Code looks good. However, the readme.md needs to be updated with at least a brief description of the approach and how to apply it. Updates should include at least the following sections:
- https://github.com/nasa/CompDam_DGD/blob/master/readme.md#shear-nonlinearity
- https://github.com/nasa/CompDam_DGD/blob/master/readme.md#material-properties
- https://github.com/nasa/CompDam_DGD/blob/master/readme.md#state-variables

2018-10-09 19:45 UTC, aFrankLion commented on tests/IM7-8552.props
> +// Schaefer Theory (values below are from Schaefer's PPT)
I do not think we will include Joe's PowerPoint files detailing the derivations and curve fitting in the repository. The off-axis tension and compression tests and data were published in an American Society for Composites paper, see:
https://ntrs.nasa.gov/search.jsp?R=20170010326

2018-10-15 13:27 UTC, aFrankLion approved these changes

2018-10-15 13:27 UTC, merged